asmtms\setcp /d TREND.ASM    
asmtms\setcp /d TODO.ASM     
asmtms\setcp /d ADC_V_P5.ASM 
asmtms\setcp /d ANAL_END.ASM 
asmtms\setcp /d AN_SP_UP.ASM 
asmtms\setcp /d BP206.ASM    
asmtms\setcp /d BP206BSS.ASM 
asmtms\setcp /d BP206CON.ASM 
asmtms\setcp /d BP206DEF.ASM 
asmtms\setcp /d BP206MAC.ASM 
asmtms\setcp /d BP206SEC.ASM 
asmtms\setcp /d BP206VEC.ASM 
asmtms\setcp /d BPADCPRO.ASM 
asmtms\setcp /d BPAVRPRG.ASM 
asmtms\setcp /d BPDISPL.ASM  
asmtms\setcp /d BPFLASH.ASM  
asmtms\setcp /d BPFLASHP.ASM 
asmtms\setcp /d BPFLASHS.ASM 
asmtms\setcp /d BPIDLE.ASM   
asmtms\setcp /d BPINIT.ASM   
asmtms\setcp /d BPINTKEY.ASM 
asmtms\setcp /d BPINTTIM.ASM 
asmtms\setcp /d BPINTU.ASM   
asmtms\setcp /d BPMODE.ASM   
asmtms\setcp /d BPSERIAL.ASM 
asmtms\setcp /d BPTABLE.ASM  
asmtms\setcp /d BP_INIT.ASM  
asmtms\setcp /d BP_MODUL.ASM 
asmtms\setcp /d CH_PR_HS.ASM 
asmtms\setcp /d DAC_CHCK.ASM 
asmtms\setcp /d DIVISION.ASM 
asmtms\setcp /d EKGTABLE.ASM 
asmtms\setcp /d F206POW.ASM  
asmtms\setcp /d F206POW2.ASM 
asmtms\setcp /d F206POW_.ASM 
asmtms\setcp /d HISTORY.ASM  
asmtms\setcp /d INDAC.ASM    
asmtms\setcp /d MAX_ANAL.ASM 
asmtms\setcp /d MEAS_FIN.ASM 
asmtms\setcp /d OLDADCPR.ASM 
asmtms\setcp /d PRESSAUG.ASM 
asmtms\setcp /d PRESS_M.ASM  
asmtms\setcp /d PROCEDUR.ASM 
asmtms\setcp /d PR_A_STP.ASM 
asmtms\setcp /d PR_A_T40.ASM 
asmtms\setcp /d PR_DIMIN.ASM 
asmtms\setcp /d PUL_F_E.ASM  
asmtms\setcp /d ST_SHIFT.ASM 
asmtms\setcp /d bp_debug.asm 
asmtms\setcp /d bp_ekg.asm   
asmtms\setcp /d bp_ekg_s.asm 
asmtms\setcp /d bp_noekg.asm 
asmtms\setcp /d bp_par_d.asm 
asmtms\setcp /d bp_paral.asm 
asmtms\setcp /d bpekgd.asm   
asmtms\setcp /d bpekgsd.asm  
asmtms\setcp /d bpnekgs.asm  
asmtms\setcp /d bpnekgsd.asm 
asmtms\setcp /d bpserold.asm 
asmtms\setcp /d bugs.asm     
asmtms\setcp /d pr_dim1.asm  
asmtms\setcp /d pr_dim2.asm  
