#!/usr/bin/perl

replace("AR7","AR8");
replace("AR6","AR7");
replace("AR5","AR6");
replace("AR4","AR5");
replace("AR3","AR4");
replace("AR2","AR3");
replace("AR1","AR2");
replace("AR8","AR1");


sub replace
{
local($from) = $_[0];
local($to) = $_[1];
print "Replace \"$from\" by \"$to\"\n";
@file=<./*\.[Aa][Ss][Mm]>;

foreach $file (@file)
 {

  open(FILE,"<$file") || die("Can't open file $file:$!\n");
  @dat=<FILE>;
  close(FILE);

  open(FILE,">$file") || die("Can't create file $file:$!\n");
  foreach $line (@dat){
   $line=~ s/$from/$to/gmi;
   print FILE $line;
   } 
  close(FILE);
 }
}
